// "use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './navbar';
import Provider from "@/context/Provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Opinion",
  description: "Generated by create next app",
};

// px-[1.5rem] sm:px-[6rem]
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className}  bg-background flex items-center flex-col `}
            >
                <Provider>
                    <div className="w-[80%] flex flex-col-reverse sm:flex-col  gap-10 ">
                        <Navbar />
                        {children}
                        <Toaster />
                    </div>
                </Provider>
            </body>
        </html>
    );
}
