import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Opinion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col bg-background px-[6rem] gap-10`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
